### ISSUE TITLE
what's the mean about bad pod #8

### ISSUE THREAD

**Issue by chips79** [SunWeb3Sec/Kubernetes-security#1]
sorry，i don‘t the mean about bad pod#8 nothing allowed

**Comment by SunWeb3Sec** [comment]
for more detail related bad pod#8, you can check: https://github.com/BishopFox/badPods/tree/main/manifests/nothing-allowed

**Comment by chips79** [comment]
> for more detail related bad pod#8, you can check: https://github.com/BishopFox/badPods/tree/main/manifests/nothing-allowed

thanks for answer and document link，I  recently know that the words is  mean a way to pentest or killchain in kubernetes

**Comment by SunWeb3Sec** [comment]
hey, you're welcome!
